name: flutter_sficon
description: 'Cross-platform Flutter plugin for rendering tree shakable SF Symbols version 5.1. inside custom widget, based on Text widget.'
version: 1.1.2
repository: https://github.com/gle6as/flutter_sficon

platforms:
    android:
    ios:
    linux:
    macos:
    web:
    windows:

environment:
    sdk: '>=3.2.3 <4.0.0'
    flutter: '>=1.17.0'

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    fonts:
        - family: sficons
          fonts:
              - asset: lib/fonts/sficons.ttf
